apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cookbook-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookbook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookbook-app
  template:
    metadata:
      labels:
        app: cookbook-app
    spec:
      containers:
        - name: cookbook-app
          image: docker.io/shehanhetti/cookbook:latest # not push to repo use local image
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
            protocol: TCP
          volumeMounts:
          - mountPath: /opt/cookbook/instance
            name: instance-vol
        - name: nginx-testrun
          image: docker.io/mioja/sensorhub-nginx:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: HOSTNAME
            value: localhost
      volumes:
      - name: instance-vol
        persistentVolumeClaim:
          claimName: cookbook-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cookbook-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: cookbook-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001